### ISSUE TITLE
[Question] Is it possible to jump to the start / enddate in DateRangePicker

### ISSUE THREAD

**Issue by orangecoding** [react-dates/react-dates#1824]
Hi,

if I preselect start and end date to for instance 01-01-2019 - 12-31-2019, the start date is shown if the user clicks on the start date field and therefor opens the picker. If the picker stay open and the user clicks on the end date, I want the picker to jump to the end date.

If the picker is closed, I can do this with the "initialVisibleMonth", but how can I do it when the picker is closed?

**Comment by leonalicious** [comment]
![image](https://user-images.githubusercontent.com/4065175/67180410-1e7ffd00-f40c-11e9-942b-eb80c3219b6b.png)


you may try something with `focusedInput`, i attached my coding for your reference
@orangecoding
