### ISSUE TITLE
[IE11] No classes applied to days in calendar

### ISSUE THREAD

**Issue by pedroabreu** [react-dates/react-dates#611]
I'm running into an issue with the calendar when accessing in IE11. It seems that the classes are not being applied to the days, so I don't have any background on the dates

![unnamed](https://user-images.githubusercontent.com/1194888/27768697-ad78af26-5f11-11e7-8cd2-7e857f52eae4.png)

From what I could understand, the issue is related to https://github.com/airbnb/react-dates/blob/721380596c239bd8b45ad514778377b2ad3ba089/src/components/CalendarDay.jsx#L94 where only the `CalendarDay` is applied to the element. 

I'm bundling the airbnb-browser-shims but it doesn't seem to make any difference. I've also tried to use polyfill.io because the issue seemed to be related to the Array.from not being supported in IE11 but also no luck with that.

Wondering if anyone is running into this issue. I'm using the latest version of react-dates (12.2.2)

**Comment by vikoultsev** [comment]
@pedroabreu 
Try to use this:
```
          'core-js/modules/es6.array.from.js',
          'core-js/modules/es6.set.js',
          'core-js/modules/es6.array.iterator.js',
```

**Comment by pedroabreu** [comment]
Totally forgot about this one. I've managed to fix this by going with core-js polyfills like @vikoultsev 

```
import "core-js/es6/array"
import "core-js/es6/set"
import "core-js/es6/symbol"
```

I've defined as one of the entry files for webpack and karma. Fixed the issue although it increased a bit the bundle size, not sure if it's actually worth it if compared to the performance gains but fair enough 👍

**Comment by ljharb** [comment]
@vikoultsev @pedroabreu we recommend https://npmjs.com/airbnb-browser-shims; the core-js Set/Map implementations aren't spec-compliant, and Symbol can't be truly polyfilled.

**Comment by ljharb** [comment]
I'm not sure why airbnb-browser-shims wouldn't be fixing this; @pedroabreu could you provide a jsfiddle that reproduces the problem?
